
Input: function-1-1.cpp main-1-1.cpp
	g++ function-1-1.cpp main-1-1.cpp -o input

Hexa: function-2-1.cpp main-2-1.cpp
	g++ function-2-1.cpp main-2-1.cpp -o hex
	./hex < test

comp: function-3-1.cpp main-3-1.cpp
	g++ function-3-1.cpp main-3-1.cpp -o comp
	./comp < test

Rev:  function-3-2.cpp main-3-2.cpp
	g++ function-3-2.cpp main-3-2.cpp -o rev
	./rev < test
