ints: function-1-1.cpp main-1-1.cpp
	g++ function-1-1.cpp main-1-1.cpp -o ints
	./ints

Color: function-2-1.cpp main-2-1.cpp
	g++ function-2-1.cpp main-2-1.cpp -o color
	./color

oe: function-3-1.cpp main-3-1.cpp
	g++ function-3-1.cpp main-3-1.cpp -o oe
	./oe

sparse: function-4-1.cpp main-4-1.cpp
	g++ function-4-1.cpp main-4-1.cpp -o sparse
	./sparse